FROM maven:3.9.9-eclipse-temurin-21

WORKDIR /app

COPY ./docker-entrypoint.sh /docker-entrypoint.sh

RUN apt-get update && apt-get install -y inotify-tools
RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]