-- Audit logging table for com.firomsa.inventory.model.AuditLog.
-- Mirrors the JPA entity so Hibernate `validate` passes (Spring physical naming -> snake_case).
-- correlation_id/action/timestamp/status are NOT NULL per the entity; old_value/new_value are
-- jsonb (@JdbcTypeCode SqlTypes.JSON); error_message is TEXT.

-- audit_logs
CREATE TABLE audit_logs (
    id            BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    correlation_id UUID        NOT NULL,
    user_id       UUID,
    username      VARCHAR(255),
    action        VARCHAR(255) NOT NULL,
    resource_type VARCHAR(100),
    resource_id   UUID,
    old_value     JSONB,
    new_value     JSONB,
    ip_address    VARCHAR(45),
    user_agent    VARCHAR(500),
    timestamp     TIMESTAMP(6) NOT NULL,
    status        VARCHAR(255) NOT NULL,
    error_message TEXT,
    CONSTRAINT pk_audit_logs PRIMARY KEY (id)
);

-- Indexes declared on the @Table(indexes = {...}) mapping.
CREATE INDEX idx_audit_correlation_id ON audit_logs (correlation_id);
CREATE INDEX idx_audit_user_id ON audit_logs (user_id);
CREATE INDEX idx_audit_action ON audit_logs (action);
CREATE INDEX idx_audit_resource_type ON audit_logs (resource_type);
CREATE INDEX idx_audit_timestamp ON audit_logs (timestamp);
CREATE INDEX idx_audit_status ON audit_logs (status);
