spring.application.name=inventory

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# swagger
springdoc.swagger-ui.path=/docs

# s3
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}
spring.cloud.aws.s3.region=${AWS_REGION}
spring.cloud.aws.s3.endpoint=${AWS_S3_ENDPOINT}