spring.application.name=inventory
spring.datasource.driver-class-name=org.postgresql.Driver

management.endpoints.web.exposure.include=health,info,metrics,loggers
management.endpoint.health.show-details=when_authorized
management.info.env.enabled=true

info.app.name=Inventory Management System
info.app.description=A simple inventory management system built with Spring Boot and PostgreSQL.
info.app.version=1.0.0
info.app.author=Firomsa Assefa